project_includes = ["source"]
project_excludes = ["**/__pycache__/**", "**/.[!/.]*", "**/tests"]

search_path = ["source"]
site_package_path = ["./.venv/lib/python3.13/site-packages"]

python_platform = "linux"
python_version = "3.13"
python_interpreter = "./.venv/bin/python3"

ignore_errors_in_generated_code = true
use_untyped_imports = true
ignore_missing_source = true

# disable `bad-override` for the whole project
[errors]
bad-assignment = false
bad-override = false
